### ISSUE TITLE
SD-Snatcher and other disk game not autoloading

### ISSUE THREAD

**Issue by Kelvfimer** [libretro/fmsx-libretro#113]
Hell

I was using fb7b19c303a95d62dd51ce72a37e70b49c529e36 and I updated to 11fa9f3c08cde567394c41320ca76798c2c64670 and for example SD Snatcher is not autoloading anymore. You can download the version I'm using here https://www.box.com/s/dlyslgvr9vs8hvpohxll 

I have also other cas and disk files that where autoloading that are not autoloaded.

is it any change on how it works?

thx

**Comment by golvellius** [comment]
Hello, 

Same problem for me.

thx

**Comment by Kelvfimer** [comment]
@cayce-msx pls can you help on this issue? When listing using files is reporting "disk i/o error" and I think that's the reason it is not running well... thx for your support.

**Comment by Kelvfimer** [comment]
For more info Latest version working is https://github.com/libretro/fmsx-libretro/commit/624834f7efa7602b5b1fa73524576de9120d942b and starting https://github.com/libretro/fmsx-libretro/commit/10c852c8c43923665d5f98a1a8b44082297953fe it ends in BASIC screen.

**Comment by Kelvfimer** [comment]
Ok I found the root cause. The issue is due to MSXDOS2.rom and DISK.ROM. If MSXDOS2.rom is presented it seems to run DISK 2.1 and it doesn't recognized snatcher. if you remove MSXDOS2.rom it works. @golvellius @cayce-msx

**Comment by haojiezhu** [comment]
> Ok I found the root cause. The issue is due to MSXDOS2.rom and DISK.ROM. If MSXDOS2.rom is presented it seems to run DISK 2.1 and it doesn't recognized snatcher. if you remove MSXDOS2.rom it works. @golvellius @cayce-msx

Glad to see a fix finally. Are you able to figure out how to use SCC/SCC+ sound with fMSX core in the English translated version of "SD Snatcher" on Windows? SCC/SCC+ works fine in the Japanese version of "SD Snatcher" on Windows. What is even stranger is that fMSX core on PSP can use SCC/SCC+ just fine in the English version:

https://www.youtube.com/watch?v=w-Z86cXhB3k

For some reason, SCC/SCC+ in fMSX just won't work properly in my tests on Windows with the English version. blueMSX core does have proper SCC/SCC+ sound in the English version.

**Comment by Kelvfimer** [comment]
Hello

it's true is not working SCC nor SCC+. FMSX 6-0 Standalone version works fine... I opened a new issue.

thx
________________________________
De: haojiezhu ***@***.***>
Enviado: sábado, 21 de enero de 2023 22:38
Para: libretro/fmsx-libretro ***@***.***>
Cc: Kelvfimer ***@***.***>; Author ***@***.***>
Asunto: Re: [libretro/fmsx-libretro] SD-Snatcher and other disk game not autoloading (Issue #113)


Ok I found the root cause. The issue is due to MSXDOS2.rom and DISK.ROM. If MSXDOS2.rom is presented it seems to run DISK 2.1 and it doesn't recognized snatcher. if you remove MSXDOS2.rom it works. @golvellius<https://github.com/golvellius> @cayce-msx<https://github.com/cayce-msx>

Glad to see a fix finally. Are you able to figure out how to use SCC/SCC+ sound with fMSX core in the English translated version of "SD Snatcher" on Windows? SCC/SCC+ works fine in the Japanese version of "SD Snatcher" on Windows. What is even stranger is that fMSX core on PSP can use SCC/SCC+ just fine in the English version:

https://www.youtube.com/watch?v=w-Z86cXhB3k

For some reason, SCC/SCC+ in fMSX just won't work properly in my tests on Windows with the English version. blueMSX core does have proper SCC/SCC+ sound in the English version.

**Comment by cayce-msx** [comment]
@Kelvfimer thanks for your patience - and requesting you to have a little more. I'm busy wrapping up a few other (personal) projects and was planning on returning to lr-fmsx in a month or so. I intended to attempt adding proper FM-PAC emulation, but I guess I'll first have to fix this one - and #115 ;)

BTW please confirm these SHA1 hashes (SD-Sn Melancholia) - link above is not working for me. Let me know if you're using another version, otherwise I could be looking/debugging in a wrong direction.
9d12c20f71c4049f8a8b65cc4f13fd7b54affadc  disk 1
4983041e918acd599e65c70de3101011c43b059a  disk 2
815ce00d94630db9cc732afa01aa8ef1f7f8bc61  disk 3

**Comment by Kelvfimer** [comment]
Yes those are the Melancholia one, but for this bug concerning MSXDOS2.rom it is hapenning with the Spanish SD SNATCHER . You can download it from here http://msx2.org/Biblioteca/Juegos%20MSX/MSX-2/_Juegos%20DSK/  It's the SP version

**Comment by cayce-msx** [comment]
@Kelvfimer just filed a PR. It appears SD-Snatcher (and a few other games) just won't boot with MSX-DOS2.
I experienced the same with `openmsx -machine Boosted_MSX2_EN [-ext msxdos2] -diska SDSN-A.dsk` - OpenMSX also doesn't start SD-Snatcher with extension msxdos2 enabled, and runs it fine without the option.

Since it's a bit of a hassle to remove MSXDOS2.ROM from you BIOS folder every time you want to start a game that doesn't run with it ;), I added a new option that by default ignores MSXDOS2.ROM. Only by explicitly enabling the option, e.g., for a specific game, MSX-DOS2 will now be loaded.
