### ISSUE TITLE
Question to cayce-msx

### ISSUE THREAD

**Issue by twinaphex** [libretro/fmsx-libretro#68]
Hi there @cayce-msx , since you seem to be quite knowledgeable about this emulator/core, I'd like to ask a question -

* MIDI logging - is this something we could take out of the core? Does it serve any purpose from a pure gameplay perspective for the user, or is it something only developers would ever care about and it has no practical purpose? I think it's probably best for this core's sake to remove as many non-essential parts as possible so that whatever we need to backport from future versions concerns only the core MSX emulator code instead of all the auxiliary stuff around it.

Thanks in advance.

**Comment by twinaphex** [comment]
Hi @cayce-msx ,

so I went ahead and removed it.

https://github.com/libretro/fmsx-libretro/commit/4075730c82b69d9be4dd3acdcec72884dfa2f250

Can you check if it has no repercussions for regula gameplay? The MIDI soundtrack logging itself doesn't seem to be a function of the MSX itself so I felt it was good to remove this to reduce some further file I/O from the core and also to boil this core down to its base essentials. Let me know if things are good/safe.

**Comment by cayce-msx** [comment]
@twinaphex I can see nothing that would break by this commit. I tested a few games (PSG, SCC & FM-PAC) and heard only expected sound/music.

MIDILogging could only be turned on/off in the in-emulator menu of fMSX, which is left out of this port (sort-of replaced by RGUI). So it was indeed unreachable code.

It appeals to gamers wanting to record the in-game music to MIDI for later playback. I guess if someone wants that, they'll have to run fMSX proper. Or maybe use openMSX to save to WAV.

> you seem to be quite knowledgeable about this emulator/core
Well, I did use it 20yrs back to finally finish Dragon Slayer 6, but haven't revisited retro gaming since about 2 years ago. And never looked at its code until a few months back. openMSX and BlueMSX are more feature rich, but openMSX has no LR port, and BlueMSX is not updated since 2009. I find fMSX a compact emulator, and am surprised at how easy it is to understand (at least part) of the code. I thought it deserved a bit of touching up.

Note that there's more that could be removed (I have a few things on my list), but I'd appreciate if we could do that _after_ the update to 6.0. That makes the diff/patch a bit less cumbersome. So if you could hold back more cleanups for just a few weeks until I have the 4.9 > 6.0 upgrade done?

**Comment by twinaphex** [comment]
Sure, I will hold off until you are done with the backports.
