### ISSUE TITLE
Feature request: creating empty disk images through libretro interface

### ISSUE THREAD

**Issue by ofry** [libretro/fmsx-libretro#91]
Related to https://github.com/libretro/fmsx-libretro/issues/43#issuecomment-979826975

It can "work" in PC. But if I launch core from some hacked game console with CFW? Or I have Lakka without direct access to shell etc.?

etc. etc.

Related to #90. If we have libretro SRAM interface, so all "new-created empty disks with some content placed by core" we can store via libretro SRAM interface.

**Comment by cayce-msx** [comment]
Sure, I can build this. But just out of curiosity: what would you _use_ this functionality for on a game console (without physical keyboard)? 

Note that a virtual keyboard is not there (see #22 - would require a modification to RetroArch itself) so there would be no way to enter a BASIC program - which is the only thing you can do with an empty disk; an empty disk makes an MSX boot into the MSX-BASIC prompt (REPL, to use a more modern term ;).

**Comment by gingerbeardman** [comment]
Some games require an empty user disk for saves.

eg. The Golf (1989, Pack-In-Video)

https://www.generation-msx.nl/software/pack-in-video/the-golf/1121/

https://gamefaqs.gamespot.com/msx/953282-the-golf/faqs/77373/loading

**Comment by cayce-msx** [comment]
Ah. That would only be useful for multidisk games. I just implemented that using m3u files. Adding an empty disk to that set beforehand would seem more intuitive to me. But, if you guys really think you can benefit from it I'll whip up some code. There's an RGUI menu option to append a fresh image to the set. Note that I have no way of saving that, since there is no file name given. That'll have to wait until #90.

**Comment by cayce-msx** [comment]
Hey @ofry @gingerbeardman I just pushed an implementation for this at https://github.com/cayce-msx/fmsx-libretro/tree/create-empty-disk-images. Could you compile & test that, to see if this is what you are looking for? If you're not able to build yourself, I could also directly send a PR to autechre, but preferably I'd first have your feedback before doing that. Otherwise just scroll through the code (I'm hoping you both can read C?). Be sure to also verify the new section 'Creating empty disk images' in the readme against your expectations.

Note: I also saw the SRAM issues (both are for the same thing, I'm assuming?). I'll pick those up separately.

**Comment by gingerbeardman** [comment]
I'm away for holiday break right now so can't build for a week. FWIW

**Comment by ofry** [comment]
@cayce-msx could you do this for cassette tape too?

**Comment by cayce-msx** [comment]
I'll repeat what I just stated in #40: "As for tape, I'll leave that for someone else to build." This issue is about creating _disk_ images, and I'm happy keeping that scope.

You have a way of keeping a person busy ;)

**Comment by ofry** [comment]
OK. Then you can make the PR from https://github.com/cayce-msx/fmsx-libretro/tree/create-empty-disk-images and close this issue.
