### ISSUE TITLE
Feature request: cheevos support

### ISSUE THREAD

**Issue by ofry** [libretro/fmsx-libretro#92]
Retroachievements project already has MSX support, and developed achievements for some MSX games: https://retroachievements.org/gameList.php?c=29

**Comment by cayce-msx** [comment]
@ofry @gingerbeardman could you give some background info and/or assistance for this one? I found:
- https://retroachievements.org/download.php mentions MSX twice
- https://docs.retroachievements.org/RALibretro/ does NOT mention MSX, although it is listed in the first URL?!
- https://docs.libretro.com/guides/retroachievements/#cores-compatibility mentions **blueMSX**, **FinalBurn Neo** (? didn't know that supported MSX) and **fMSX** - the latter as _"Emulation is too unstable to support"_
- I found no info how to implement cheevos / achievements, so I looked through libretro-fceumm, libretro-bluemsx and RetroArch itself
   - **libretro-fceumm** sets `RETRO_ENVIRONMENT_SET_SUPPORT_ACHIEVEMENTS` 
   - docs for that: _"If true, the libretro implementation supports achievements either via memory descriptors set with RETRO_ENVIRONMENT_SET_MEMORY_MAPS **or** via retro_get_memory_data/retro_get_memory_size"_
   -  **libretro-fceumm** implements **both** `retro_get_memory_size/data()` for `RETRO_MEMORY_SAVE_RAM` and `RETRO_MEMORY_SYSTEM_RAM` **and** calls `RETRO_ENVIRONMENT_SET_MEMORY_MAPS()`
   - **blueMSX** **only** implements `retro_get_memory_size/data()` for `RETRO_MEMORY_SYSTEM_RAM`
   - .. so I'm a bit puzzled how blueMSX would then qualify for cheevos? It doesn't adhere to the API, it seems, so why is it listed as Supported ✔ at https://docs.libretro.com/guides/retroachievements/#cores-compatibility?
- **fMSX**: any idea why _"Emulation [would be] too unstable to support"_? I know of no stability issues with fMSX. Granted, it's very limited in accuracy. That might indeed be an issue for hardcore gamers that want to achieve, well, achievements ;). But that's not what this statement says..
- note: libretro-fmsx also implements `retro_get_memory_size/data()` for `RETRO_MEMORY_SYSTEM_RAM`, just like libretro-bluemsx. So if blueMSX works, then so should fMSX.
- the RetroArch code, in `consoleinfo.c`, contains this section:```
/* ===== MSX ===== */
/* https://www.msx.org/wiki/The_Memory */
/* MSX only has 64KB of addressable RAM, of which 32KB is reserved for the system/BIOS.
 * However, the system has up to 512KB of RAM, which is paged into the addressable RAM
 * We expect the raw RAM to be exposed, rather than force the devs to worry about the
 * paging system. The entire RAM is expected to appear starting at $10000, which is not
 * addressable by the system itself.
 */
static const rc_memory_region_t _rc_memory_regions_msx[] = {
    { 0x000000U, 0x07FFFFU, 0x010000U, RC_MEMORY_TYPE_SYSTEM_RAM, "System RAM" },
};
static const rc_memory_regions_t rc_memory_regions_msx = { _rc_memory_regions_msx, 1 };
```
Now, what does all this mean? Is it in any way used in the cheevos system?
Also, I have no clue what "The entire RAM is expected to appear starting at $10000" exactly means. I see both bluemsx & fmsx just exposing the entire RAM as a block in `retro_get_memory_size/data()`, without any additional 'formatting'.

I have no experience with cheevos myself, and am far from a hardcore gamer, so I don't see myself testing this one. I'm hoping one of you have a retroachievements account? At the least, I'd be very grateful if someone could tell me which core was used to gain the achievements logged for the 16 games listed at the URL ofry sends above. So that I might look at the code for that one, and see how it implements the cheevos API.

**Comment by gingerbeardman** [comment]
I've never used them before, I doubt I will in future.

From my understanding the memory is made available so one or more addresses can be monitored for specific values that will trigger the achievement.

**Comment by cayce-msx** [comment]
Thanks for responding so quickly! Then I'll await @ofry for some more info - for starters: "which core was used to gain the achievements logged for the 16 games listed".

**Comment by ofry** [comment]
@cayce-msx You should communicate with @Jamiras for this. He deals most of cheevos support on Retroarch. I'm only user of Retroachievements, not a dev there.

**Comment by ofry** [comment]
@cayce-msx As I read on https://docs.retroachievements.org/Emulator-Support-and-Issues/ achievements should be working on BlueMSX core.

**Comment by Jamiras** [comment]
From a core's perspective, all you have to do to support achievements is expose the memory properly and not modify the game files. `RETRO_ENVIRONMENT_SET_SUPPORT_ACHIEVEMENTS` defaults to true, so it's not necessary to explicitly call it.

As you've already found, this is the important information:
```
/* ===== MSX ===== */
/* https://www.msx.org/wiki/The_Memory */
/* MSX only has 64KB of addressable RAM, of which 32KB is reserved for the system/BIOS.
 * However, the system has up to 512KB of RAM, which is paged into the addressable RAM
 * We expect the raw RAM to be exposed, rather than force the devs to worry about the
 * paging system. The entire RAM is expected to appear starting at $10000, which is not
 * addressable by the system itself.
 */
static const rc_memory_region_t _rc_memory_regions_msx[] = {
    { 0x000000U, 0x07FFFFU, 0x010000U, RC_MEMORY_TYPE_SYSTEM_RAM, "System RAM" },
};
static const rc_memory_regions_t rc_memory_regions_msx = { _rc_memory_regions_msx, 1 };
```
The first three columns are the RetroAchievements start and end addresses, and the "real" address of the memory. For MSX, we don't actually ask for the memory from the real address, as the memory exposed from $8000-$FFFF is paged in via a memory mapper. As such, we virtualize the full unpaged memory at $10000 (outside the normally addressable space for the system).

The real address is only important if you expose the memory via `RETRO_ENVIRONMENT_SET_MEMORY_MAPS`. When using `RETRO_ENVIRONMENT_SET_MEMORY_MAPS`, we attempt to match the provided segments in the exposed memory maps to their corresponding RetroAchievements blocks by mapping the real address to the start/select/disconnect fields of the `retro_memory_descriptor`.

When using `retro_get_memory_data`/`retro_get_memory_size`, we fill the `RC_MEMORY_TYPE_SYSTEM_RAM` RetroAchievements block from the `RETRO_MEMORY_SYSTEM_RAM` return values (truncating or null padding as necessary), and any `RC_MEMORY_TYPE_SAVE_RAM` RetroAchievements blocks from the `RETRO_MEMORY_SAVE_RAM` return values. The MSX memory map doesn't have a `RC_MEMORY_TYPE_SAVE_RAM` RetroAchievements block, so you only need to handle the `RETRO_MEMORY_SYSTEM_RAM` case.

The important thing about supporting achievements for MSX is the way the paged memory is exposed. As long as you can do that in a way that mimics blueMSX (as all current achievements have been developed using that), that should be all you need to do.

The only other thing that might matter to the core is that the game identification process requires the source media to be read only. If the system supports writable media, any modifications to the "ROM" files need to be segregated into the `retro_serialize` functionality, or it may cause the game to not be identified on future loads.

I apologize that many of our documentation links are out-of-sync and/or out-of-date.

**Comment by cayce-msx** [comment]
@Jamiras thanks for the explanation! I got an account, cfg'd RA, prepped the right hash for SD-Snatcher (that actually took the most time!) and bingo - I 'achieved' "Welcome to JUNKER" using fmsx-libretro (git commit 51e50ebd), in RetroArch on Linux - see https://retroachievements.org/user/cayce. No code changes required!

@ofry please test this on your setup. Note that e.g. Aleste doesn't start without setting the ROM mapper to 'ASCII 16kB'. I'll test the other 15 games too (didn't test SD-Snatcher with multi-disk yet).

**Comment by Jamiras** [comment]
Glad to hear.

> in RetroArch v1.7.3
I'm kind of surprised that worked. That version of RetroArch is almost four years old. The current version is 1.9.14. We've completely rewritten the achievement runtime and added a lot of new features since then.

**Comment by cayce-msx** [comment]
That's the version that comes with my Ubuntu package manager. I also tried on a fresh git commit, built locally. Works fine too. I do indeed see quite some UI changes!

**Comment by cayce-msx** [comment]
@Jamiras any idea why "[fMSX] emulation [would be] too unstable to support", who wrote that & when? (https://docs.libretro.com/guides/retroachievements/#msx-msx2) Would be nice to update, now that cheevos are working. (I documented some prerequisites in this core's readme in a PR just now.)

**Comment by Jamiras** [comment]
It looks like it was added here: https://github.com/libretro/docs/pull/517
@Sanaki goes by KickMeElmo on discord.

**Comment by Sanaki** [comment]
Yeah, I need to fix that. There were some issues with the core back when I wrote that, but it looks damn good now. It's been on my todo list, but my health has kept me from doing much lately. Still, I'll see about updating that page later today, because that definitely has aged poorly.

**Comment by Sanaki** [comment]
PR submitted for the doc update: libretro/docs#692

I did notice some missing image warnings in the fMSX docs page, but that's an issue for someone with more time.

**Comment by ofry** [comment]
OK. So I can close it...
